title: My blog for GitHub learning
author: Pavel
email: hwmaster2@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My first time to do blog on GitHub

# social links
twitter_username: hwmaster2
github_username:  hwmaster2

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
